name: zedd
description: A voice control app to open other applications.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  http: ^1.2.2
  url_launcher: ^6.0.9
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.6
  lottie: ^1.2.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/animation.json
  uses-material-design: true
